name: 'node-express-api-dev'
services:
    db:
        image: postgres
        restart: always
        env_file:
            - ../env/.env
        ports:
            - 5433:5432 # db:5432 -> localhost:5433
        volumes:
            - pgdata:/var/lib/postgresql/data
    server:
        image: node-express-api-dev
        build:
            context: ..
            target: server-dev
            dockerfile: docker/Dockerfile
        env_file:
            - ../env/.env
        ports:
            - 3000:3000
        depends_on:
            - db
        volumes:
            - ../server:/home/app/server
            - prisma_generated:/home/app/server/src/generated
            - node_modules:/home/app/server/node_modules

volumes:
    pgdata:
    prisma_generated:
    node_modules:
